version: '3.8'

services:
  mycookbook-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - proxy-net
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys

networks:
  proxy-net:
    external: true

volumes:
  dataprotection-keys:
    driver: local