version: '3.8'

services:
  mycookbook-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:{WEB_PORT:-8080}
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true