services:
  mycookbook-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PFX_CERT_PASSWORD}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ~/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro

  db:
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 1s
      timeout: 1s
      retries: 1
      start_period: 1s