services:
  mycookbook-app:
    build:
      context: .
      dockerfile: MyCookbook/Dockerfile
    container_name: mycookbook-app
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyCookbookDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - mycookbook-network

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mycookbook-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - mycookbook-network

networks:
  mycookbook-network:
    driver: bridge

volumes:
  mssql-data:
    driver: local