services:
  mycookbook-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PFX_CERT_PASSWORD}
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ~/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro

  db:
    env_file:
      - .env
    ports:
      - "1433:1433"